# Generated by Django 5.2.7 on 2026-01-12 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_book_category_remove_book_publication_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcopy',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='bookcopy',
            name='copy_type',
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='copy_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Borrowed', 'Borrowed'), ('Reference Only', 'Reference Only')], default='Available', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='app.book'),
        ),
    ]
