# Generated by Django 5.2.7 on 2026-01-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_bookcopy_availability_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='copy_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Borrowed', 'Borrowed')], default='Available', max_length=20),
        ),
    ]
