# Generated by Django 5.2.7 on 2026-01-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_bookcopy_copy_number_alter_bookcopy_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcopy',
            options={'ordering': ['copy_number']},
        ),
        migrations.AlterUniqueTogether(
            name='bookcopy',
            unique_together={('book', 'copy_number')},
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='availability_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Reference Only', 'Reference Only'), ('Unavailable', 'Unavailable')], default='Available', max_length=50),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='copy_type',
            field=models.CharField(choices=[('Printed', 'Printed'), ('PDF', 'PDF'), ('eBook', 'eBook')], default='Available', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='copy_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name='bookcopy',
            name='status',
        ),
    ]
